# Generated by Django 4.2.11 on 2024-11-23 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spot_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_handicapped', models.BooleanField(default=False)),
                ('is_charging', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Parking Spot',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Parked',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('qr', models.ImageField(blank=True, upload_to='qr_codes')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.parkingspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parked',
            },
        ),
    ]
