# Generated by Django 4.2.11 on 2025-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_reservation_qr_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_time'], 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='reservation_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
