# Generated by Django 4.2.11 on 2025-03-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parked',
            name='exceeded_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
