# Generated by Django 4.2.11 on 2025-05-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_logistics_summary_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parked',
            name='parking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
