# Generated by Django 4.2.11 on 2025-06-08 16:13

from django.db import migrations, models
import park.models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0008_reservation_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reference_number',
            field=models.CharField(blank=True, default=park.models.create_rand_id, editable=False, max_length=255, null=True),
        ),
    ]
